language: node_js
node_js:
  - "12"
addons:
  apt:
    sources:
      - sourceline: 'ppa:js-reynaud/kicad-5.1'
    packages:
      - inkscape
      - kicad
env:
  - CACHED_BUILD=cached
script:
  - bash keep_alive.sh &
  - export NODE_ENV=production
  - ./scripts/plug_versions
  - ./scripts/get_boards production $CACHED_BUILD
  - ./configure production $CACHED_BUILD
  - wget https://github.com/ninja-build/ninja/releases/download/v1.6.0/ninja-linux.zip
  - unzip ninja-linux.zip
  - if  [ "${CACHED_BUILD}" != "cached" ]; then ./ninja clean; fi
  - ./ninja -j 2 && cp registry.json build/
  - yarn smoke-test
  - ./scripts/deploy
cache:
  yarn: true
  directories:
    - ./build
    # needed to cache folder with Cypress binary
    - ~/.cache
